on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v6
        with:
          source: "dist/"
          bucket: "${{ secrets.S3_BUCKET_NAME }}"
          region: "${{ secrets.S3_BUCKET_REGION }}"
          access_key_id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Invalidate CloudFront cache (Optional)
        uses: reggionick/invalidate-cloudfront-cache@v3
        with:
          distribution-id: "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
          paths: "/*"